class BloodGroup
{ 
public static void main(String[] args)
{
String password="Sushmita@123";
System.out.println(password);
String welCome="Have a Great Day";
System.out.println(welCome);
String laptop="Chummi123";
System.out.println(laptop);
String type = "Java programming";
System.out.println(type);
String first = "Java";
System.out.println(first);
String second = "Python";
System.out.println(second);
String third = "JavaScript";
System.out.println(third);
String greet = "Hello! World";
System.out.println(greet);
String example = "This is the  class";
System.out.println(example );
String str1 ="Hi";
System.out.println(str1);
String str2 ="friends";
System.out.println(str2);
String str3 ="java world";
System.out.println(str3);
String str4 ="friends";
System.out.println(str4);
String stdName = "sufiyan";
System.out.println(stdName);
String scalerAcad = "Scaler Academy";
System.out.println(scalerAcad);
String val1 = "Personal ";
System.out.println(val1);
String val2 = "Computer";
System.out.println(val2);
String genre = "action";
System.out.println(genre);
String str = "lets do party"; 
System.out.println(str); 
String str44 = "have a good weekend";
System.out.println(str4); 
String str5 = "its very beautyfull";  
System.out.println(str5); 
String str6 = " its a topics";
System.out.println(str6);  
String str7="A Dog is barking";
System.out.println(str7);  
String str8="A colour of books";
System.out.println(str8);  
String str9="A colour of toys";
System.out.println(str9);  
String val3="a very beautyfull Ballon";
System.out.println(val3);
String val4="A boy is very handsome";
System.out.println(val4);
String val5="A girl is too preety";
System.out.println(val5);
String val6="lets play football";
System.out.println(val6);
String val7="i love barbii";
System.out.println(val7);
String val8="i love my family";
System.out.println(val8);
String val9="the serial is intersting";
System.out.println(val9);
String happy="i am very happy today";
System.out.println(happy);
String newspaper="i read newspaper every day";
System.out.println(newspaper);
String booksReading=" i am very intrested in reding a story books";
System.out.println(booksReading);
String table="the laptop is on the table";
System.out.println(table);
String wildAnimals="wild animals present in zoo";
System.out.println(wildAnimals);
String numbers="a numbers starts from 0";
System.out.println(numbers);
String farmAnimals="farm & pet animals";
System.out.println(farmAnimals);
String alphabets="a alphabets starts from A & ends with Z";
System.out.println(alphabets);
String flowers="a beautyfull flowers";
System.out.println(flowers);
String people="people at work";
System.out.println(people);
String animals="a rabbit is preety animal";
System.out.println(animals);
String colours=" i like purple colour";
System.out.println(colours);
String speker="its loud";
System.out.println(speker);
String bag=" we carry laptop in bag";
System.out.println(bag);
String google="we browse information in google";
System.out.println(google);
String bootel="store water in bottel";
System.out.println(bootel);
String sheep="a sheep sound baa";
System.out.println(sheep);
String wolf="a wolf is a wild animal";
System.out.println(wolf);
String fork="we eat some food with fork";
System.out.println(fork);
String sun="a morning sunlight is good for health";
System.out.println(sun);
String sunlight="a sunlight gives light for us";
System.out.println(sunlight);
String towel="we use towle for wash";
System.out.println(towel);
String about="about me";
System.out.println(about);
String seeds="some seeds good for health";
System.out.println(seeds);
String god="we worship god every day";
System.out.println(god);
String toysbaby="babies like a toys";
System.out.println(toysbaby);
String air="air helps to breath us";
System.out.println(air);
String pillow="we use pillow to sleep";
System.out.println(pillow);
String food="my faviourate food is western food";
System.out.println(food);
String charger="we use charger for charging";
System.out.println(charger);
String eyes="we use eyes to see everthing";
System.out.println(eyes);
String chair="we use cahir to sit";
System.out.println(chair);
String cricket="cricket is one of the intersting game";
System.out.println(cricket);
String tomato="tomato is in red in colour";
System.out.println(tomato);
String chilli="chilli are in different in colour";
System.out.println(chilli);
String rose="rose is in red colour";
System.out.println(rose);
String mouse="mouse is a parts of computer";
System.out.println(mouse);
String health="health is wealth";
System.out.println(health);
String pincode="Vrushanka@8722";
System.out.println(pincode);
String goodDay="Have a beautiful Day";
System.out.println(goodDay);
String mobile="navi123";
System.out.println(mobile);
String progType = "Javascript programming";
System.out.println(progType);
String zero = "HTML";
System.out.println(zero);
String five = "we use spring booth in projects";
System.out.println(five);
String six = "we use backend as a database";
System.out.println(six);
String greeting = "Hii Good morning Have a Great Day";
System.out.println(greeting);
String example1 = "This is  the java training center";
System.out.println(example1);
String xworkzs="we go to x-workzs daily by morning session";
System.out.println(str1);
String english ="its one of the language";
System.out.println(str2);

      }
}